name: Build and Deploy .NET App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  # Adjust this to your target .NET version

      # Step 3: Debugging step to find .csproj
      - name: Find Project Files
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing Files:"
          ls -la
          echo "Finding .csproj file:"
          find . -name "*.csproj"

      # Step 4: Build the .NET project
      - name: Build .NET Project
        run: dotnet build --configuration Release
        working-directory: ./path/to/project-directory # Update this with the path to the .csproj file directory

      # Optional: Publish the application
      - name: Publish Application
        run: dotnet publish --configuration Release --output ./publish
        working-directory: ./path/to/project-directory # Update with the correct directory
