name: Build and Deploy .NET App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  # Adjust to your target .NET version

      # Step 3: Locate project directory (Optional Debugging)
      - name: Debug project directory
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in Directory:"
          ls -la
          echo "Finding .csproj file:"
          find . -name "*.csproj"

      # Step 4: Navigate to the project directory and build the project
      - name: Build .NET project
        run: dotnet build --configuration Release
        working-directory: ./path/to/project-directory # Replace with the relative path to your project

      # Step 5: Deploy or publish (optional)
      - name: Publish App (Optional)
        run: dotnet publish --configuration Release --output ./publish
        working-directory: ./path/to/project-directory
